### ISSUE TITLE
Update Cookiecutter questions

### ISSUE THREAD

**Issue by IgnacioHeredia** [ai4os/ai4-template#10]
Now that everything will be hosted under `ai4os-hub` I don't think it makes sense to keep showing users the `git_base_url` parameter. We can keep having it as a hidden variable though.

I also think something similar  for `app_version`. If you are creating the template you would want always the version to be 0.0.1 right? Does it make sense to be configurable?

Finally, I will add to the help message of `project_name` that it is the name of the python module. Otherwise, people tend to use very lengthy names that look ugly.

**Comment by vykozlov** [comment]
+1 for "ai4o-hub" and git_base_url
for "app_version", I would keep it configurable, someone may consider their version not "0.0.1" if the certain code already existed
to be on the safe side, I put that tin to-do :-)

**Comment by BorjaEst** [comment]
git_base_url is now "private" so we can change it easily in the future
project_name  prompt updated
