### ISSUE TITLE
Check Dokcer repo and tag?

### ISSUE THREAD

**Issue by IgnacioHeredia** [ai4os/ai4-template#12]
@BorjaEst @vykozlov 
Maybe it makes sense to have a step in the cookiecutter preprocessing to check that the repo+tag submitted by the user do indeed exist in DockerHub.

This can be done easily using the DockerHub API.

**Comment by BorjaEst** [comment]
We did something similar in EOSC Perf, the main constrain was when users want to use images located at nvidia hub or other personal hubs, let me take a look.

**Comment by IgnacioHeredia** [comment]
Yes. Well, we can always detect if the repo belong to DockerHub and if so, perform this check. Otherwise, skip it.

**Comment by BorjaEst** [comment]
Just to mention, draw back is the cookiecutter becomes dependent on the user internet connection when creating the project (no problem from Templates Hub I hope) and from that docker hub is also up. I suppose nevertheless it should be ok.

**Comment by IgnacioHeredia** [comment]
Yes. Maybe add a timeout, and if DockeHub does not respond, proceed anyway without errors.

**Comment by vykozlov** [comment]
Hi @BorjaEst and @IgnacioHeredia ,

do we talk about "docker_baseimage"? and "baseimage_tag"?
If so, do we really need to check them? hub.docker.com in the meantime is not the only Docker repository, e.g.:

- ghcr.io - from Github
- nvcr.io - from Nvidia
- quay.io - from RedHat

in the end, there are custom deployed Harbor instances..

Also "docker_baseimage" appears only in the Dockerfile, i.e. it will immediately clear for the user why the build fails, if Docker image name:tag is wrong.

Like that, I do not see a value in having this check, or?

**Comment by IgnacioHeredia** [comment]
It's true that is is a fixable error, as it does not spread much.

So I'm fine not checking it, especially since, as you say, can potentially come from anywhere.
Feel free to close the issue.
