### ISSUE TITLE
Minor errors in fresh install

### ISSUE THREAD

**Issue by IgnacioHeredia** [ai4os/ai4-template#2]
Noticed the following.

Just after fresh download:
1) All files are staged
2) Except README, which is partially staged, but which has the following line unstaged:
```
 [![Build Status](https://jenkins.services.ai4os.eu/buildStatus/icon?job=AI4OS-hub/ai4os-demo-app/test)](https://jenkins.services.ai4os.eu/job/AI4OS-hub/job/ai4os-demo-app/job/main/)
```

Regarding 2), the line is inconsistent as it should point to either `test` or `main`, not both. Given that the templates starts in the `test` branch, test is then.
Regarding 1) and 2), I rather stage everything or unstage everything. Personally I think it is clearer to not stage anything and let the user do it.

**Comment by vykozlov** [comment]
Item 1. - was a problem in templates-hub, there was no default git user to do first commit
Item 2. - resolved in @900ec3f
